spring:
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
  datasource:
    url: jdbc:mysql://localhost:3306/sw?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 23456789